/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestDriveRouteImport } from './routes/test-drive'
import { Route as SellRouteImport } from './routes/sell'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as CatalogueRouteImport } from './routes/catalogue'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as VehicleIdRouteImport } from './routes/vehicle.$id'
import { Route as AdminVehiclesRouteImport } from './routes/admin.vehicles'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTestDrivesRouteImport } from './routes/admin.test-drives'
import { Route as AdminSellRequestsRouteImport } from './routes/admin.sell-requests'
import { Route as AdminRlsCheckRouteImport } from './routes/admin.rls-check'
import { Route as AdminEnquiriesRouteImport } from './routes/admin.enquiries'
import { Route as AdminContentRouteImport } from './routes/admin.content'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'

const TestDriveRoute = TestDriveRouteImport.update({
  id: '/test-drive',
  path: '/test-drive',
  getParentRoute: () => rootRouteImport,
} as any)
const SellRoute = SellRouteImport.update({
  id: '/sell',
  path: '/sell',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogueRoute = CatalogueRouteImport.update({
  id: '/catalogue',
  path: '/catalogue',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const VehicleIdRoute = VehicleIdRouteImport.update({
  id: '/vehicle/$id',
  path: '/vehicle/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVehiclesRoute = AdminVehiclesRouteImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTestDrivesRoute = AdminTestDrivesRouteImport.update({
  id: '/test-drives',
  path: '/test-drives',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSellRequestsRoute = AdminSellRequestsRouteImport.update({
  id: '/sell-requests',
  path: '/sell-requests',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRlsCheckRoute = AdminRlsCheckRouteImport.update({
  id: '/rls-check',
  path: '/rls-check',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEnquiriesRoute = AdminEnquiriesRouteImport.update({
  id: '/enquiries',
  path: '/enquiries',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/catalogue': typeof CatalogueRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/finance': typeof FinanceRoute
  '/sell': typeof SellRoute
  '/test-drive': typeof TestDriveRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/enquiries': typeof AdminEnquiriesRoute
  '/admin/rls-check': typeof AdminRlsCheckRoute
  '/admin/sell-requests': typeof AdminSellRequestsRoute
  '/admin/test-drives': typeof AdminTestDrivesRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/vehicles': typeof AdminVehiclesRoute
  '/vehicle/$id': typeof VehicleIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/catalogue': typeof CatalogueRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/finance': typeof FinanceRoute
  '/sell': typeof SellRoute
  '/test-drive': typeof TestDriveRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/enquiries': typeof AdminEnquiriesRoute
  '/admin/rls-check': typeof AdminRlsCheckRoute
  '/admin/sell-requests': typeof AdminSellRequestsRoute
  '/admin/test-drives': typeof AdminTestDrivesRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/vehicles': typeof AdminVehiclesRoute
  '/vehicle/$id': typeof VehicleIdRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/catalogue': typeof CatalogueRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/finance': typeof FinanceRoute
  '/sell': typeof SellRoute
  '/test-drive': typeof TestDriveRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/enquiries': typeof AdminEnquiriesRoute
  '/admin/rls-check': typeof AdminRlsCheckRoute
  '/admin/sell-requests': typeof AdminSellRequestsRoute
  '/admin/test-drives': typeof AdminTestDrivesRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/vehicles': typeof AdminVehiclesRoute
  '/vehicle/$id': typeof VehicleIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/catalogue'
    | '/compare'
    | '/contact'
    | '/finance'
    | '/sell'
    | '/test-drive'
    | '/admin/audit'
    | '/admin/content'
    | '/admin/enquiries'
    | '/admin/rls-check'
    | '/admin/sell-requests'
    | '/admin/test-drives'
    | '/admin/users'
    | '/admin/vehicles'
    | '/vehicle/$id'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/catalogue'
    | '/compare'
    | '/contact'
    | '/finance'
    | '/sell'
    | '/test-drive'
    | '/admin/audit'
    | '/admin/content'
    | '/admin/enquiries'
    | '/admin/rls-check'
    | '/admin/sell-requests'
    | '/admin/test-drives'
    | '/admin/users'
    | '/admin/vehicles'
    | '/vehicle/$id'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/catalogue'
    | '/compare'
    | '/contact'
    | '/finance'
    | '/sell'
    | '/test-drive'
    | '/admin/audit'
    | '/admin/content'
    | '/admin/enquiries'
    | '/admin/rls-check'
    | '/admin/sell-requests'
    | '/admin/test-drives'
    | '/admin/users'
    | '/admin/vehicles'
    | '/vehicle/$id'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  CatalogueRoute: typeof CatalogueRoute
  CompareRoute: typeof CompareRoute
  ContactRoute: typeof ContactRoute
  FinanceRoute: typeof FinanceRoute
  SellRoute: typeof SellRoute
  TestDriveRoute: typeof TestDriveRoute
  VehicleIdRoute: typeof VehicleIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test-drive': {
      id: '/test-drive'
      path: '/test-drive'
      fullPath: '/test-drive'
      preLoaderRoute: typeof TestDriveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell': {
      id: '/sell'
      path: '/sell'
      fullPath: '/sell'
      preLoaderRoute: typeof SellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogue': {
      id: '/catalogue'
      path: '/catalogue'
      fullPath: '/catalogue'
      preLoaderRoute: typeof CatalogueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/vehicle/$id': {
      id: '/vehicle/$id'
      path: '/vehicle/$id'
      fullPath: '/vehicle/$id'
      preLoaderRoute: typeof VehicleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/vehicles': {
      id: '/admin/vehicles'
      path: '/vehicles'
      fullPath: '/admin/vehicles'
      preLoaderRoute: typeof AdminVehiclesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/test-drives': {
      id: '/admin/test-drives'
      path: '/test-drives'
      fullPath: '/admin/test-drives'
      preLoaderRoute: typeof AdminTestDrivesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sell-requests': {
      id: '/admin/sell-requests'
      path: '/sell-requests'
      fullPath: '/admin/sell-requests'
      preLoaderRoute: typeof AdminSellRequestsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/rls-check': {
      id: '/admin/rls-check'
      path: '/rls-check'
      fullPath: '/admin/rls-check'
      preLoaderRoute: typeof AdminRlsCheckRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/enquiries': {
      id: '/admin/enquiries'
      path: '/enquiries'
      fullPath: '/admin/enquiries'
      preLoaderRoute: typeof AdminEnquiriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAuditRoute: typeof AdminAuditRoute
  AdminContentRoute: typeof AdminContentRoute
  AdminEnquiriesRoute: typeof AdminEnquiriesRoute
  AdminRlsCheckRoute: typeof AdminRlsCheckRoute
  AdminSellRequestsRoute: typeof AdminSellRequestsRoute
  AdminTestDrivesRoute: typeof AdminTestDrivesRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminVehiclesRoute: typeof AdminVehiclesRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditRoute: AdminAuditRoute,
  AdminContentRoute: AdminContentRoute,
  AdminEnquiriesRoute: AdminEnquiriesRoute,
  AdminRlsCheckRoute: AdminRlsCheckRoute,
  AdminSellRequestsRoute: AdminSellRequestsRoute,
  AdminTestDrivesRoute: AdminTestDrivesRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminVehiclesRoute: AdminVehiclesRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  CatalogueRoute: CatalogueRoute,
  CompareRoute: CompareRoute,
  ContactRoute: ContactRoute,
  FinanceRoute: FinanceRoute,
  SellRoute: SellRoute,
  TestDriveRoute: TestDriveRoute,
  VehicleIdRoute: VehicleIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
